### ISSUE TITLE
Can't build on Debian 8 with sbcl - MAGIC_NONE issue?

### ISSUE THREAD

**Issue by quicklisp** [dochang/magicffi#4] opened 2016-01-07 15:53 UTC
I get this:

```
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1003DD5663}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10108C410B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10108C40DB}>)
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SB-SYS:FD-STREAM for "file /home/quicklisp/quicklisp-controller/tmp/anonymous/anonymous-ElI8Fms3/depcheck-fail.txt" {1005E1E343}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CFFI-GROVEL:GROVEL-ERROR "External process exited with code ~S.~@
         Command was: ~S~{ ~S~}~@
         Output was:~%~A" {10108C11A3}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<CFFI-GROVEL:GROVEL-ERROR "External process exited with code ~S.~@
         Command was: ~S~{ ~S~}~@
         Output was:~%~A" {10108C11A3}>)
6: (INVOKE-DEBUGGER #<CFFI-GROVEL:GROVEL-ERROR "External process exited with code ~S.~@
         Command was: ~S~{ ~S~}~@
         Output was:~%~A" {10108C11A3}>)
7: (ERROR CFFI-GROVEL:GROVEL-ERROR :FORMAT-CONTROL "External process exited with code ~S.~@
         Command was: ~S~{ ~S~}~@
         Output was:~%~A" :FORMAT-ARGUMENTS (1 "gcc" ("-m64" "-I/home/quicklisp/quicklisp-controller/dist/build-cache/cffi/e7921b040f0a965a2604c95da10e039387059c22/cffi_0.16.1/" "-o" "/home/quicklisp/.cache/common-lisp/sbcl-1.3.1-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/magicffi/f57e33399d16c5043b9cca6580993ef4caae284d/magicffi-20160107-git/grovel" "/home/quicklisp/.cache/common-lisp/sbcl-1.3.1-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/magicffi/f57e33399d16c5043b9cca6580993ef4caae284d/magicffi-20160107-git/grovel.c") "/home/quicklisp/.cache/common-lisp/sbcl-1.3.1-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/magicffi/f57e33399d16c5043b9cca6580993ef4caae284d/magicffi-20160107-git/grovel.c: In function ‘main’:
/home/quicklisp/.cache/common-lisp/sbcl-1.3.1-linux-x64/home/quicklisp/quicklisp-controller/dist/build-cache/magicffi/f57e33399d16c5043b9cca6580993ef4caae284d/magicffi-20160107-git/grovel.c:411:25: error: ‘MAGIC_NONE’ undeclared (first use in this function)
   fprintf(output, \"%i\", MAGIC_NONE);
             ^
```

Log is here: http://report.quicklisp.org/2016-01-06/failure-report/magicffi.html#magicffi

**Comment by dochang** [comment] 2017-08-13 15:45
Unable to reproduce here.  Close it now.  Feel free to give me feedback.

**Closed by dochang** 2017-08-13 15:45 UTC
